name: Deploy Website

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v1
      - name: Install surge, firebase and deploy
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: npm install
      - run: npm install -g surge
      - run: npm install -g firebase-tools
      - run: npm run build --if-present
      - run: surge ./build ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
      - run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
